### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by 1001v** [AurityLab/vue-recaptcha-v3#1]
Hello. In my app i make several async uploads simultaneously and try to get a unique token for each of them. The problem is that i get a timeout error in most cases. I just wanted to ask, if this is a normal behavior and we can only have one token at the same time, or this is a throttle from google's servers, or this is a bug. Thank you.

**Comment by WipeAir** [comment]
Hi, I've just tried to reproduce your issue by starting 20 requests simultaneously. It looks like they will be executed sequentially, but at all each of the requests got a response with a valid token.
You may setup a demo project, where you can reproduce it, so I can look into it. But at all I'm assuming it's a limitation from Google.

**Comment by 1001v** [comment]
[Here it is](https://github.com/1001v/recaptcha-timeout-demo). You probably should press that button a few times, but this works different any time, sometimes it's enough to request only 5 recaptchas to get errors. During requests please take a look at network activity. The interesting thing is, that when we get errors, the appropriate requests could be still finished successfully. You can see it on these screenshots:
![image](https://user-images.githubusercontent.com/7795325/48670036-683bd580-eb21-11e8-8bd4-af8346c2c071.png)
![image](https://user-images.githubusercontent.com/7795325/48670039-7d186900-eb21-11e8-9bae-92139fce3402.png)

**Comment by WipeAir** [comment]
Ok, I've tried it with your demo project. But all my requests were successfully processed (I've clicked the button ~10x).
But on your screenshots I can see that the origin of the error is the recaptcha script from Google, so I assume it's a limitation from Google (maybe even country dependent).
So maybe you can try to reach out to Google and ask them about this limitation issue.

**Comment by 1001v** [comment]
@WipeAir just interesting, which browser did you use?

**Comment by WipeAir** [comment]
I've tested it with Chromium version 70, which one did you use?

**Comment by 1001v** [comment]
@WipeAir i've tested it with some chromium browsers and firefox. The interesting thing is that this issue doesn't appear in firefox at all. I've written a letter to google about it.

**Comment by WipeAir** [comment]
Ok, that's pretty strange. Have you actually tried to reproduce it without this plugin?
Can you keep me informed about the response from Google here?

**Comment by 1001v** [comment]
@WipeAir hello. I didn't received any response from google, but i noticed that the problem is gone, at least i can't reproduce it anymore. Maybe they've fixed something silently.

**Comment by WipeAir** [comment]
Hi,
that was actually as expected...
But it's nice to hear, that your problem is solved now :)
