### ISSUE TITLE
How do I display the captcha icon only on certain pages (VUE reCAPTCHA-v3)?

### ISSUE THREAD

**Issue by positivethinking639** [AurityLab/vue-recaptcha-v3#102]
I use this package : https://www.npmjs.com/package/vue-recaptcha-v3. It get from this github

I add on my main.js : 

    import { VueReCaptcha } from 'vue-recaptcha-v3'
    
    Vue.use(VueReCaptcha, { siteKey: 'xxxxxxx' })

I add this code :

    await this.$recaptcha('login').then((token) => {
        recaptcha = token
    })

to my component to get token from google recapchta

My problem is the captcha icon in the lower right corner appears on all pages

[![enter image description here][1]][1]

I want it to only appear in certain components

Maybe I must to change this : `    Vue.use(VueReCaptcha, { siteKey: 'xxxxxxxxxxxxxxxxx' })`. Seems it still mounting to `Vue.use`. I want to mount to a certain component instead of vue root instance 

How can I solve this problem?

  [1]: https://i.stack.imgur.com/ufp8S.png

**Comment by WipeAir** [comment]
Hey,
I've just published v1.7.2 which exposes [`ReCacaptchaInstance`](https://github.com/AurityLab/recaptcha-v3/blob/master/src/ReCaptchaInstance.ts). You can now call `this.$recaptchInstance.hideBadge()` to hide and `this.$recaptchInstance.showBadge()` to show the ReCaptcha badge.

**Comment by nateiler** [comment]
For what it's worth, this is my implementation via Vue 3 to show/hide the badge on a specific page

```typescript
import { Vue , Ref } from 'vue';

import { ReCaptchaInstance } from 'recaptcha-v3';
import { VueReCaptcha } from 'vue-recaptcha-v3';

const RECAPTCHA_SITE_KEY = 'RECAPTCHA_KEY';

// Route names where we 'show' the badge
const RECAPTCHA_ROUTE_NAMES = ['register'];

const app = Vue.createApp({});

app.use(VueReCaptcha, { siteKey: RECAPTCHA_SITE_KEY, autoHideBadge: true });

const recaptchaLoaded = app.config.globalProperties
  .$recaptchaLoaded as () => Promise<boolean>;

void recaptchaLoaded().then(() => {
  const instance = app.config.globalProperties
    .$recaptchaInstance as Ref<ReCaptchaInstance>;

  function toggleReCaptcha(routeName: string) {
    RECAPTCHA_ROUTE_NAMES.includes(routeName)
      ? instance.value.showBadge()
      : instance.value.hideBadge();
  }

  toggleReCaptcha(<string>(router.currentRoute.value.name || ''));

  router.beforeEach((to, _from, next) => {
    toggleReCaptcha(<string>(to.name || ''));
    next();
  });
});

```

**Comment by rwaddin** [comment]
Maybe this can help someone https://github.com/AurityLab/vue-recaptcha-v3/issues/588#issuecomment-1278738989 :smiley:
