### ISSUE TITLE
not work in mobile browser

### ISSUE THREAD

**Issue by huuhait** [AurityLab/vue-recaptcha-v3#112]
Hi bro! i have tested recatcha it work really good but in mobile it cant work
can u check and fix it?

**Comment by WipeAir** [comment]
Hi, what exactly does not work?

**Comment by huuhait** [comment]
Hi, cant get token from recaptcha
maybe your function not work in mobile .-. i have tested in UC and chrome but it not work at all...

**Comment by WipeAir** [comment]
Do you have any error messages?
I can't help you without error messages, because it can't reproduce your problem.

**Comment by huuhait** [comment]
![image](https://user-images.githubusercontent.com/40519768/70569168-ffac1480-1bcb-11ea-86fa-691f6ad3576b.png)
ah it working normal
sorry my bad
i forgot xD
i dont add ip for mobile connect to pc

tks for your support :D
