### ISSUE TITLE
Remove Plugin on destroy

### ISSUE THREAD

**Issue by happynautpro** [AurityLab/vue-recaptcha-v3#173]
Hi,

is there an easy way to remove or delete Recaptcha with the destroy() lifecycle hook?

**Comment by WipeAir** [comment]
Hey, there is actually no way to completely remove/destroy the reCAPTCHA on your site. It's actually intended by Google to have the reCAPTCHA loaded on all your sites ([see here](https://developers.google.com/recaptcha/docs/v3#placement_on_your_website)).
I'd be possible to implement a destroy for this plugin, but this would only have an impact on the plugin itself and not on the actual reCAPTCAH instance.
