### ISSUE TITLE
TypeError: _this.$recaptcha is not a function

### ISSUE THREAD

**Issue by BeetrootShoulders** [AurityLab/vue-recaptcha-v3#222]
Get this error when I try to use the package in my Vue app. Package is imported in my main app.js file and in the component. Using code copied from the examples. No idea how to fix.

**Comment by aklinker1** [comment]
See [this section to setup a typescript shim file](https://github.com/aklinker1/vue-recaptcha-v3/tree/vue-3-support#typescript--vue-3), similar to the `shims-vue.d.ts` and `shims-tsx.d.ts`. It just adds types to you components. That is on a fork for vue 3, but if you tweak it a bit, it should work, maybe look at the other shims to see if there's some similaries? Maybe [something like this](https://github.com/AurityLab/vue-recaptcha-v3/blob/5574aaab9b540a5bd756c9b1087ecbdf34ef86f4/src/ReCaptchaVuePlugin.ts#L43)?

```ts
// any/path/in/the/project/shims-vue-recaptcha-v3.d.ts
import { ReCaptchaInstance } from 'recaptcha-v3'

declare module 'vue/types/vue' {
  interface Vue {
    $recaptcha: (action: string) => Promise<string>
    $recaptchaLoaded: () => Promise<boolean>
    $recaptchaInstance: ReCaptchaInstance
  }
}
```

I don't remember having this issue with vue2 though

**Comment by WipeAir** [comment]
Could you provide a snippet of your project which shows how you use the plugin? And the full error (incl. stacktrace) would be great!
