### ISSUE TITLE
Uncaught TypeError: vue_1.ref is not a function

### ISSUE THREAD

**Issue by SergeyNeroda** [AurityLab/vue-recaptcha-v3#287]
If the library is connected:

import { VueReCaptcha } from "vue-recaptcha-v3";
Vue.use(VueReCaptcha, { siteKey: "your-public-key" });

an error occurs:
vue_1.ref is not a function

**Comment by SergeyNeroda** [comment]
Help me)

**Comment by SergeyNeroda** [comment]
Object.defineProperty(exports, "__esModule", { value: true });
exports.useReCaptcha = exports.VueReCaptcha = void 0;
var recaptcha_v3_1 = __webpack_require__(/*! recaptcha-v3 */ "./node_modules/recaptcha-v3/dist/ReCaptcha.js");
var vue_1 = __webpack_require__(/*! vue */ "./node_modules/vue/dist/vue.common.js");
var VueReCaptchaInjectKey = Symbol('VueReCaptchaInjectKey');
var globalConfig = {
    loadedWaiters: [],
    error: null
};
exports.VueReCaptcha = {
    install: function (app, options) {
        var isLoaded = vue_1.ref(false);
        var instance = vue_1.ref(undefined);
        app.config.globalProperties.$recaptchaLoaded = recaptchaLoaded(isLoaded);
        initializeReCaptcha(options).then(function (wrapper) {
            isLoaded.value = true;
            instance.value = wrapper;
            app.config.globalProperties.$recaptcha = recaptcha(instance);
            app.config.globalProperties.$recaptchaInstance = instance;
            globalConfig.loadedWaiters.forEach(function (v) { return v.resolve(true); });
        }).catch(function (error) {
            globalConfig.error = error;
            globalConfig.loadedWaiters.forEach(function (v) { return v.reject(error); });
        });
        app.provide(VueReCaptchaInjectKey, {
            instance: instance,
            isLoaded: isLoaded,
            executeRecaptcha: recaptcha(instance),
            recaptchaLoaded: recaptchaLoaded(isLoaded)
        });
    }
};

**Comment by WipeAir** [comment]
Looks like you're using Vue 2.*. The latest version of this library is for Vue 3.
See [here](https://github.com/AurityLab/vue-recaptcha-v3/issues/281#issuecomment-733812821)

**Comment by SergeyNeroda** [comment]
Thanks
