### ISSUE TITLE
this.$recaptcha is not a function"

### ISSUE THREAD

**Issue by WangXang** [AurityLab/vue-recaptcha-v3#3]
**error: this.$recaptcha is not a function"**

index.js：
############################
import Vue from 'vue'

import { sync } from 'vuex-router-sync'
// store
import store from "./store.js"
......
import { VueReCaptcha } from "vue-recaptcha-v3"
Vue.use(VueReCaptcha,{siteKey:"6LdwmHcUAAAAAH2jppzD3vcK3f7Rr8H7Krm1-TMg"})
############################
components：
this.$recaptcha("login").then((token) => {
                console.log("谷歌Token:"+ token)
            })

**Comment by WipeAir** [comment]
Hey,
this is actually intended, to wait until the reCAPTCHA is fully loaded you can use the
`$recaptchaLoaded()` function (See [here](https://github.com/AurityLab/vue-recaptcha-v3/blob/master/src/ReCaptchaVuePlugin.ts#L11)). It will return a Promise which will be resolved as soon as reCAPTCHA is loaded.
I'll add a full example on how to use it to the readme soon.

**Comment by WangXang** [comment]
Thanks, when capacchachaLoaded is loaded, recaptcha can be used, but for the user, this is not a good experience. Because it takes a long time to load (of course it depends on the network environment used)
` beforeMount(){
        this.$store.commit('showLoadingByGobal',true)
        this.body_status = false
        this.$recaptchaLoaded().then(() => {
            this.$recaptcha("login").then(
                (token) => {
                    this.recaptchatoken = token
                    console.log("GooGle Token:"+token)
                    this.initDetail()  // real request and get data
                }
            )         
        })
    }`

**Comment by WipeAir** [comment]
That's true, but this behavoir is fully dependent on Google.
