### ISSUE TITLE
issue  vue_1.ref is not a function

### ISSUE THREAD

**Issue by alirezahamid** [AurityLab/vue-recaptcha-v3#300]
Hi, when I want to just set up this package as this [guideline ](https://github.com/AurityLab/vue-recaptcha-v3#usage) everything goes wrong. and I got this error `ReCaptchaVuePlugin.js?7eae:49 Uncaught TypeError: vue_1.ref is not a function`. any way to solve this problem?

**Comment by WipeAir** [comment]
I guess you're using Vue 2, therefore you need to use this [guide](https://github.com/AurityLab/vue-recaptcha-v3/tree/vue-v2.x). (You need to use `^1.9.0` as version constraint)

**Comment by alirezahamid** [comment]
Thanks a million, @WipeAir problem is solved.
