### ISSUE TITLE
timeout-or duplicate error

### ISSUE THREAD

**Issue by TamerElMorsi** [AurityLab/vue-recaptcha-v3#325]
i tried to submit some form to server 
then the form was validated on server side and asked client to fill some data
when i submitted the form again recaptcha raise **timeout-or duplicate error** 
here is my script code at GoogleRecaptcaV3.vue file

  export default {
        name:'GoogleRecaptcaV3',
        props: {
            action: {
                type: String,
                required: true
            }
        },
created() {
            this.recaptcha();
        },
        methods: {
            // setting for vue 2.x
                async recaptcha() {
                // (optional) Wait until recaptcha has been loaded.
                await this.$recaptchaLoaded()
                // Execute reCAPTCHA with action "appoinmentRequest".
                const token = await this.$recaptcha(this.action)
                this.tokenKey = token;
            },
        },
 }

**Comment by WipeAir** [comment]
Hi,
the *timeout-or-duplicate* error means that your token has been expired. To fix it, just call `this.$recaptcha` again.

See [here](https://developers.google.com/recaptcha/docs/verify#error_code_reference) for more information about the error.
