### ISSUE TITLE
Can i Add this to a login buton?

### ISSUE THREAD

**Issue by indra619** [AurityLab/vue-recaptcha-v3#347]
hi i just wanna ask can i use recaptcha in vue project that uses vuetify?,
and i want to connect the recapcha into login button, thanks

**Comment by TrayserCassa** [comment]
Yes you can, look in the examples for a complete copy paste experience :)

**Comment by WipeAir** [comment]
Hi,
yes, can use it. Take a look at the [usage example](https://github.com/AurityLab/vue-recaptcha-v3#usage).
