### ISSUE TITLE
useRecaptcha() causes error in Vue 3

### ISSUE THREAD

**Issue by bokuns** [AurityLab/vue-recaptcha-v3#399]
I always received following error when calling useRecaptcha() inside setup() function in Vue 3 (Composition API):
```
import { useRecaptcha } from 'vue-recaptcha-v3';

export default {
  ...,
  setup() {
    const { executeRecaptcha, recaptchaLoaded } = useRecaptcha(); // => TypeError: Object(...) is not a function
  }
}

/*
"vue": "^3.0.0",
"vue-recaptcha-v3": "^2.0.0",
*/
```

I've strictly followed the guideline, not sure why it goes wrong...

**Comment by WipeAir** [comment]
There's a typo in the published documentation on npm... For now you may follow the [Usage](https://github.com/AurityLab/vue-recaptcha-v3#usage) section on the master branch.
Basically, you need to use `useReCaptcha()` instead of `useRecaptcha()`.
