### ISSUE TITLE
show captcha on specific pages

### ISSUE THREAD

**Issue by asp-entwickler** [AurityLab/vue-recaptcha-v3#4]
Hello
After adding component like
 Vue.use(VueReCaptcha, { siteKey: "....." })

captcha 
![image](https://user-images.githubusercontent.com/19171449/50658378-76db3080-0f99-11e9-95e0-3fb9939a6259.png)
appear on every page of application

For now I hide in with CSS but
it would be nice to have option show it on selected pages (components)

**Comment by WipeAir** [comment]
Hi, 
such a feature is already implemented.
There are so called [loader options](https://github.com/AurityLab/vue-recaptcha-v3#options) which are passed to the [library behind this module](https://github.com/AurityLab/recaptcha-v3). To hide the badge you just have to set the `autoHideBadge` loader option. ([See here](https://github.com/AurityLab/recaptcha-v3#usage-1))

E.g.
```javascript
Vue.use(VueReCaptcha, {
  siteKey: '<site key>',
  loaderOptions: {
    autoHideBadge: true
  }
})
```

**Comment by asp-entwickler** [comment]
Thank you. Better than nothing ))
