### ISSUE TITLE
Uncaught (in promise) null

### ISSUE THREAD

**Issue by maiconschelter** [AurityLab/vue-recaptcha-v3#40]
When I use the vue-recaptcha-v3 with Webpack (^4.31.0) and VueJS (^2.3.0), after build the project, the following error promise has been occurs.

The code:
```
import { VueReCaptcha } from 'vue-recaptcha-v3';
Vue.use(VueReCaptcha, { siteKey: 'my_key' });

export default {
  name: 'my-component',
  methods: {
    get_recaptcha() {
      this.$recaptcha('social').then((token) => {
        this.load_result(token);
      });
    }
  }
};
```

The following error on console browser:
```
my-component:1 Uncaught (in promise) null
Promise.then (async)
get_recaptcha @ custom.js:34
keyup @ custom.js:48
We @ custom.js:19
n @ custom.js:19
a._wrapper @ custom.js:19
```

Any ideas from this?

**Comment by WipeAir** [comment]
Hey, can you create a simple demo project where this error occurs?

**Comment by maiconschelter** [comment]
Ok, I gonna try to make a demo project.

**Comment by maiconschelter** [comment]
Creating que demo project sample, I discovery the real problem about this. If the host domain is not valid to access using the site key, this error has been occurred. I don't see this problem at the original project because **_autoHideBadge_** is **_true_**.

![image](https://user-images.githubusercontent.com/1637379/60103737-82ccd180-9736-11e9-8219-88b7f4871734.png)

After change host domain at reCaptcha configuration panel, the problem is solved.

Many thanks!

**Comment by WipeAir** [comment]
Great to hear, that you fixed the problem by yourself! :) I may implement a better error message for this error in the next release.
