### ISSUE TITLE
How to locolize widget?

### ISSUE THREAD

**Issue by Orangat** [AurityLab/vue-recaptcha-v3#436]
How I can pass lang param to the component?

**Comment by WipeAir** [comment]
By default the language of the browser will be used. In case you want to use a fixed language, you can add "renderParameters".

Example on how to use it during the plugin initialization:
`Vue.use(VueReCaptcha, { siteKey: '<site key>', loaderOptions: {renderParameters: {"hl": "<language code>"}}})`

And [here](https://developers.google.com/recaptcha/docs/language) is a list of available language codes.

**Comment by Orangat** [comment]
Browser language is English, but recapthca still on Russsian language.

I can pass language param like this?
Vue.use(VueReCaptcha, { siteKey: '', loaderOptions: {renderParameters: {"hl": "en"}} })

**Comment by Orangat** [comment]
@WipeAir look at message above.
