### ISSUE TITLE
How to render verification popup?

### ISSUE THREAD

**Issue by J4si3k** [AurityLab/vue-recaptcha-v3#5]
every request receives a token which is checked on the backend and I get success, but I have never been able to see the verification popup window.
Should not, at least every now and then, pop up a popup window?

**Comment by WipeAir** [comment]
Hey,
sorry for the delay. This behavior is intended, because this library is made for [reCAPTCHA **v3**](https://developers.google.com/recaptcha/docs/v3).

From the [official docs](https://developers.google.com/recaptcha/docs/v3):
> reCAPTCHA v3 returns a score for each request without user friction. The score is based on interactions with your site and enables you to take an appropriate action for your site.
