### ISSUE TITLE
Feature request: Actions

### ISSUE THREAD

**Issue by bigoper** [AurityLab/vue-recaptcha-v3#55]
## Actions
- reCAPTCHA v3 introduces a new concept: actions.

reCAPTCHA you enable two new features:

a detailed break-down of data for your top ten actions in the admin console
adaptive risk analysis based on the context of the action (abusive behavior can vary)
Importantly, when you verify the reCAPTCHA response you should also verify that the action name matches the one you expect.

```js
  grecaptcha.ready(function() {
      grecaptcha.execute('reCAPTCHA_site_key', {action: 'homepage'});
  });
```

- this feature is missing in your current implementation.

**Comment by WipeAir** [comment]
Hey,
actions are already implemented. As stated here [here](https://github.com/AurityLab/vue-recaptcha-v3#usage) you can use `this.$recaptcha('<action here>')`.

**Comment by bigoper** [comment]
@WipeAir 
Thank you so much for the quick response!

I guess working late hours has it's effects :)
Got no idea how I've missed it.

Thank you!
