### ISSUE TITLE
Latest version is not compatible to use with Vue2

### ISSUE THREAD

**Issue by pmenika** [AurityLab/vue-recaptcha-v3#558]
Hi, Since latest vue-recaptcha-v3 version doesn't support with Vue2 app, I am unable to use it with Composition API plugin in Vue2. 

https://stackoverflow.com/questions/69808528/using-vue-recaptcha-v3-with-vue-2-composition-api-plugin

**Comment by WipeAir** [comment]
There is a branch specifically for Vue 2.x. See [here](https://github.com/AurityLab/vue-recaptcha-v3/tree/vue-v2.x).

**Comment by pmenika** [comment]
Yes. But it's not the latest version. I am using Composition API with Vue2 and I am not able to use 
`const { executeRecaptcha, recaptchaLoaded } = useReCaptcha()`
in my setup function as this is not available in  `vue-recaptcha-v3@^1.9.0`

**Comment by findorf** [comment]
Any hint on using Vue 2 and composition api with this package?
