### ISSUE TITLE
CSP violation in production

### ISSUE THREAD

**Issue by berlaga** [AurityLab/vue-recaptcha-v3#562]
I host my VueJS SPA app in Azure. I get the following message when the app is loaded.

Refused to load the script 'https://www.google.com/recaptcha/api.js?render=explicit' because it violates the following Content Security Policy directive: "script-src 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.

reCaptcha docs recommend:
We recommend using the nonce-based approach documented with CSP3. Make sure to include your nonce in the reCAPTCHA api.js script tag, and we'll handle the rest.

How can I accomplish that?

**Comment by berlaga** [comment]
Just to add more details. The actual problem is in ReCaptchaLoader.js

![image](https://user-images.githubusercontent.com/19954572/140965059-905ca791-352e-4a85-8f1d-b5736d2cf27f.png)

**Comment by berlaga** [comment]
My bad. Disregard. 
I incorrectly configured Content Security Policy. For people that may encounter this: configure CSP inside your server.js. This way your Node app will set the correct CSP header regardless of IIS settings.
It works fine now.

**Comment by pouriabagheri** [comment]
Hi @berlaga would you mind sharing your CSP directives that got ReCaptcha working ?
