### ISSUE TITLE
Unexpected token { (Nuxt)

### ISSUE THREAD

**Issue by Ovyerus** [AurityLab/vue-recaptcha-v3#6]
Using Nuxt, when I try to load the library in the way shown in the examples, I get an `Unexpected token {` syntax error. My guess from looking at the bundled/compiled code in the package, is that for reason some the ES6 import/export statements are causing it, but I'm not sure.

**Comment by WipeAir** [comment]
Hey,
I haven't tried the library with Nuxt yet. I'll try to fix it and get back to you asap!

**Comment by Ovyerus** [comment]
:+1:

**Comment by WipeAir** [comment]
Sorry for the delay!
I've changed the module system to `commonjs` in v1.3.0 (already published on npm).
Hopefully it solves your problem! If you have any further problems, don't hesitate to reply.

**Comment by Ovyerus** [comment]
Looks like it's still happening. Took a look at the file again and it looks like it still has ES6 imports. Possibly forgot to rebuild for it?

**Comment by WipeAir** [comment]
You may retry it now - v1.3.1

**Comment by Ovyerus** [comment]
Alright seems to be fixed in v1.3.1 now. I seem to be getting a compile error for one of my components but unsure if it's the plugin or me. Removing it works fine though.

Thanks for the help 👍

**Comment by Ovyerus** [comment]
On second look it seems to be occuring with, any `input` element I try to make, which is bizarre.

**Comment by WipeAir** [comment]
What do you exactly mean with `input element` in this case?
The plugin is not bound to any component directly...

**Comment by Ovyerus** [comment]
Any `<input>`. When there's none in the current view it seems to work fine, but when there's one it causes an error like shown above. Not sure why exactly.

**Comment by WipeAir** [comment]
Ok, that's crazy. Is this problem reproducible in a simple Nuxt app? If so, can you provide me an example project? Then I could look into it :)

**Comment by Ovyerus** [comment]
Alright so I go to test it in a clean one, and of course it doesn't come up, even when I try testing it again in the main project. I'll try to see if I can properly recreate it if it crops up again.

**Comment by WipeAir** [comment]
Ok, good to hear that it works.
If it occurs again just create a demo project and send it to me.
