### ISSUE TITLE
How can I prevent to load recaptcha to every page

### ISSUE THREAD

**Issue by amirkhh** [AurityLab/vue-recaptcha-v3#7]
Hi, I need Recaptcha for specific page and I don't need to load this in every page. How can I do that ?

thanks.

**Comment by WipeAir** [comment]
Hey,
it's intended to always load it. Also there is no proper way to load it and then unload it later (Assuming you use it in a spa).
If you want to get rid of the reCAPTCHA badge you can use the [options](https://github.com/AurityLab/vue-recaptcha-v3#options) (specifically `loaderOptions` which provides an [`autoHideBadge` option](https://github.com/AurityLab/recaptcha-v3/#loader-options)).

**Comment by amirkhh** [comment]
I've fixed this big problem and now ReCaptcha just load in one specific page.

Remove below code from main.js:

```
import { VueReCaptcha } from 'vue-recaptcha-v3'

Vue.use(VueReCaptcha, {
    siteKey: '6Le8UX4UAAAAAHaLrHu48UHb3agFQcWW5-P0l0qc',
    /!*loaderOptions: {
        autoHideBadge: true,
    }*!/
});
```

And in your component where you want to load ReCaptcha, insert below code:

```
import Vue from 'vue';
import { VueReCaptcha } from 'vue-recaptcha-v3'

export default {
    components: {
        VueReCaptcha,
    },
    mounted() {
        VueReCaptcha(Vue, {siteKey: 'CAPTCHA_SITE_KEY'});
    },
}
```

Enjoy it.

**Comment by neXorianus** [comment]
using @amirkhh s approach the batch is only loaded when first hitting the page it needs to be on.
but after that, it stays on the site abd wont be removed/hidden
