### ISSUE TITLE
Error with sitekey

### ISSUE THREAD

**Issue by lukas1313ByMe** [AurityLab/vue-recaptcha-v3#8]
I got the error 'Invalid site key or not loaded in api.js: ', but I don't know what I have done wronge.

**Comment by WipeAir** [comment]
Hey,
this message just means something is wrong with your site key. Some possibilities:
* Is your site key set as described [here](https://github.com/AurityLab/vue-recaptcha-v3#usage)?
* Is your current domain added to the reCAPTCHA?
* Is the site key from [reCAPTCHA](https://www.google.com/recaptcha/intro/v3.html)?

You may check these points and get back here if it's still not working.
