### ISSUE TITLE
I have problem with https in production on server

### ISSUE THREAD

**Issue by mamadza** [AurityLab/vue-recaptcha-v3#9]
Hi , I have problem with recaptcha in production mode on the server and recaptcha cant loaded and I have this error: 
Content Security Policy: The page’s settings blocked the loading of a resource at https://www.google.com/recaptcha/api.js?render=6Le8UX4UAAAAAHaLrHu48UHb3agFQcWW5-P0l0qc (“script-src”).

Unhandled promise rejection Error: "Something went wrong while loading ReCaptcha. ([object Event])"

**Comment by WipeAir** [comment]
Hey,
do you have any `Content-Security-Policy` meta-tag in your html file? If so, you may check if it cause this error.

**Comment by mamadza** [comment]
thank , I checked now I find the nginx config may change to support that

**Comment by WipeAir** [comment]
Great to hear that you've fixed it :)
